### ISSUE TITLE
How does video synchronization work?

### ISSUE THREAD

**Issue by kuba-orlik** [ennuicastr/ennuicastr#26]
We've ran a test recording and got video files of guests joining at different times.

The project page says that video is synchronized with audio, but how does that synchronization work? We have video clips of different length now, is there a trick to load them to editing software and line up based on some metadata?

**Comment by Yahweasel** [comment]
If you run it through, e.g., Handbrake, it will be synced.

The way that video synchronization works is that the video when downloaded is very, very variable-framerate. The first frame lasts until the user started recording, and every other frame is at its correct time. Unfortunately, most video editing packages aren't capable of dealing with VFR video at all (let alone video that's *very* VFR), but Handbrake (and ffmpeg, etc) can turn them into constant-framerate video relatively straightforwardly.

I'm actually working on a less gross solution in the beta branch now, but that's not live yet.

**Comment by kuba-orlik** [comment]
That's brilliant, thanks! Curious about the "less gross" solution, but I'll experiment with what we have already now :+1:
