### ISSUE TITLE
Error: Could not open source file on RID ohgivv

### ISSUE THREAD

**Issue by tristanbay** [ennuicastr/ennuicastr#27]
We (Xendergarten podcast) just finished a 1 hr 28 min podcast and I was trying to download the FLAC zip file (using the simple downloader since the regular one doesn't seem to be loading or is taking forever to do so). It came out to 162 MB with several people, which is smaller than expected, and when I try opening it, the zip file is corrupt. The other person who downloaded this file is also having the same issue. The person who started the podcast had their page freeze, so they had to re-join and they couldn't stop the recording, so everyone had to leave the recording instead. Could this have been why the zip file is corrupt?

I tried the wav download and that's only 237 MB. The zip file for it is also corrupt.

**Comment by Yahweasel** [comment]
The ZIP is generated on the fly. Unfortunately, the nature of ZIP is that if it doesn't complete for any reason, it won't open (and the nature of downloading things on the web is that I have to put it in a ZIP). The audio data is almost certainly fine; just a download issue.

Can you send me privately (use any of the contact methods on https://ecastr.com/contact/ ) the download link so I can check it out?

**Comment by Yahweasel** [comment]
(Or ideally, a share link)

**Comment by tristanbay** [comment]
> (Or ideally, a share link)

I sent you the download link. If that doesn't work, I'll send you the share link

**Comment by Yahweasel** [comment]
I sent you a corrected download via email. Please don't delete the recording, as I'll be using it to diagnose and fix this for the future.

**Comment by Yahweasel** [comment]
Fixed in https://github.com/ennuicastr/ennuicastr-server/commit/4148ca64f8619133904de1b1d279a4af139a802c . Thanks for the report!
